Repository atomist/uhura, pull requests merged in 2019-04, with the labels that each got.

#16 Uses atomist-seeds provided seeds so that dashboard works with uhura
  lib/machine/nodeSeeds.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#22 Support optional transform contributors in UniversalGenerator
  lib/generate/universal/universalGenerator.ts
  package-lock.json
  package.json
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#27 Add support for sending messages from a Project Analysis
  lib/element/k8s/K8sDeployInterpreter.ts
  lib/machine/machine.ts
  lib/preference/deployment.ts
  package-lock.json
  package.json
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added, enhancement

#31 Onboarding support
  index.ts
  lib/element/docker/dockerScanner.ts
  lib/machine/defaultAnalyzerFactory.ts
  lib/machine/machine.ts
  lib/preference/pushTests.ts
  package-lock.json
  package.json
Labels: auto-merge:on-approve, changelog:added, enhancement

#29 Enhance Gradle and Maven support
  index.ts
  lib/element/docker/DockerfileInterpreter.ts
  lib/element/docker/dockerScanner.ts
  lib/element/docker/dockerStack.ts
  lib/element/dotnet/DotnetCoreInterpreter.ts
  lib/element/dotnet/dotnetCoreScanner.ts
  lib/element/gradle/gradleScanner.ts
  lib/machine/defaultAnalyzerFactory.ts
  lib/machine/machine.ts
  package-lock.json
  package.json
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed, enhancement
